### ISSUE TITLE
Question: Development - how to revert masking update? (Take 2)

### ISSUE THREAD

**Issue by AndydeCleyre** [numixproject/com.numix.icons_circle#17]
Hi,

This is a continuation of #11, which was never resolved. It was opened 4 months ago and mistakenly marked as resolved 2 months later. I believe as a consequence comments are no longer monitored.

To be clear, the question is how to restore the masking system that did not scale down the original icon and did not add a color to the background. The sought-after masking system cropped the icon to the uniform circular shape.

Thanks,
Andy

**Comment by Foggalong** [comment]
This isn't something we're supporting. The icons are scaled rather cropped so that the design style is as consistent as it can be across both our icons and the masked icons.
