### ISSUE TITLE
Fairphone launcher support

### ISSUE THREAD

**Issue by keunes** [numixproject/com.numix.icons_circle#21]
Dear team,

After installing the Numicx Circle icon pack on my laptop, I wanted to install it on my phone, too, to create an awesome consistent experience :)

However, it appears my phone's (Fairphone) launcher is not supported. Would it be possible for you guys to enable installing for their launcher/system, too ([the source code is here on GitHub as well](https://github.com/Kwamecorp/Fairphone))? Or is there a way to download and install it from source?

Thanks in any case!

**Comment by enthusiasmus** [comment]
+1

I love the numix icons :+1: and I also would appreciate a support of the fairphone launcher! Also wondered why all the supported launchers are proprietary ones... :-1:

**Comment by enthusiasmus** [comment]
Any updates on this issue?

**Comment by mueller-ma** [comment]
@enthusiasmus OpenLauncher can use the icon set. https://github.com/OpenLauncherTeam/openlauncher
