### ISSUE TITLE
RemixOS

### ISSUE THREAD

**Issue by Foggalong** [numixproject/com.numix.icons_circle#36]
From Ahjolinna ahjolinna@yahoo.com 

> I have a small request, could you please add support for RemixOS desktop like experience to your application: https://www.kickstarter.com/projects/jidetech/remix-mini-the-worlds-first-true-android-pc/posts/1371897?ref=backer_project_update

**Comment by bil-elmoussaoui** [comment]
Update: alpha version is released http://www.jide.com/en/remixos-for-pc#downloadNow

**Comment by Foggalong** [comment]
Remix OS has been out for a while now, that's just the PC version

**Comment by creepertron95** [comment]
@Foggalong Just to let you know, Remix OS has been discontinued.

**Comment by Foggalong** [comment]
Reading the Wikipedia it sound like a couple forks of this are still being developed so it's probably worth keeping this open with them in mind.
