### ISSUE TITLE
Build without Play services

### ISSUE THREAD

**Issue by Rudloff** [numixproject/com.numix.icons_circle#45]
Hello,

Apparently the app can't be built without Play services:

```
A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugCompile'.
   > Could not find com.google.android.gms:play-services:7.3.0.
```

This prevents the latest versions from being included in F-Droid.
Would it be possible to provide an option to build the app without Play services?

**Comment by satya164** [comment]
@PaoloRotolo Why do we need play services?

**Comment by Rudloff** [comment]
It looks like Play Services are used for ads and analytics.
