### ISSUE TITLE
Use candybar

### ISSUE THREAD

**Issue by bilelmoussaoui** [numixproject/com.numix.icons_circle#46]
In order to get a great experience for Android users as for Linux users, i think that we can implement https://github.com/danimahardhika/candybar-library. Which will allow us to have a better support for almost all the new launchers out there. With a great material design, icon requests and all the nice features an icon pack might need! 
My java skills are not that good but i can implement this; if you guys are okay with that :)

**Comment by mueller-ma** [comment]
I started with it here: https://github.com/mueller-ma/candybar-sample

**Comment by mueller-ma** [comment]
@bil-elmoussaoui Is there a way to automaticly built appfilter.xml ?

**Comment by bil-elmoussaoui** [comment]
I didn't start working on this (my finals are on two weeks) but i will likely create a Python script to do that automatically for me

**Comment by mueller-ma** [comment]
Ok. Here's the plan:

1. I try to finalize the customization of candybar
2. Add android acitvity to https://github.com/numixproject/numix-core/blob/master/data.json
3. Change https://github.com/numixproject/numix-core/blob/master/gen.py to use the acitivity and generate appfilter.xml and drawables.xml
4. Copy the generated images and xml file to this repo
5. Enjoy
6.

**Comment by bil-elmoussaoui** [comment]
Yeah that will be a lot of work especially adding the activities to the json file... Your current implementation works correctly? If so you can create a PR and I will try to review it as soon as possible :)

**Comment by Foggalong** [comment]
My advice /for now/ would be to leave the donations out. At some point I and the rest of the original Numix team need to have a sit down and decide what's happening financials wise, so I'll get back to you when we do.
