### ISSUE TITLE
Can't find app on Play Store

### ISSUE THREAD

**Issue by gilbertohasnofb** [numixproject/com.numix.icons_circle#54]
I have a Lenovo Moto G5 running Android 8.1.0 and I can't find Numix Circle Icon Pack in the Play Store. I can see the following apps by Numix:

* Numix Square icon pack  
* Icon Request for Numix
* Numix Hexagon icon pack
* Numix Wallpapers - Nature
* Numix Wallpapers

**Comment by Modelmat** [comment]
I can't see it either.

**Comment by alekksander** [comment]
@paolorotolo 
is there a chance for an update? :) not regarding play store only, but in general, there are many many updated icons unavailable on android yet

**Comment by creepertron95** [comment]
@alekksander We are discussing it in #55.
